[build]
command = "npm run build:production"
publish = "build"
ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF ../../"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NETLIFY_NEXT_PLUGIN_SKIP = "true"