const productions = [
  {
    id: 'inhousekitchen',
    name: 'Inhousekitchen',
    period: '',
    githubRepoName: [],
    skills: [
      'ReactNative',
      'Nativebase',
      'Expo',
      'Redux-Offline',
      'Redux',
      'Redux-Saga',
      'Storybook',
    ],
    summary: '셰프와 게스트 연결해주는 서비스',
    githubUrl: 'https://github.com/Nexters/inhousekitchen',
    linkUrl: '',
  }, {
    id: 'buxi',
    name: 'Buxi',
    period: '',
    githubRepoName: [],
    skills: [
      'ReactJS',
      'styled-component',
      'NodeJS',
      'Redux',
      'Redux-Saga',
      'Webpack',
      'Storybook',
    ],
    summary: '같은 목적지를 오가는 분들이 원하는 시간대에 함께 쓰는 새로운 카셰어링',
    githubUrl: '',
    linkUrl: 'https://www.buxikorea.com/',
  },
  {
    id: 'flass',
    name: 'Flass',
    period: '',
    githubRepoName: ['flass'],
    skills: [
      'ReactJS',
      'React-Router',
      'Mocha',
      'Redux',
      'Material UI',
      'Webpack',
      'Sass',
      'Rails',
    ],
    summary: 'Site For Flipped Learning',
    githubUrl: 'https://github.com/Nexters/flass',
    linkUrl: 'http://flass.me',
  },
  {
    id: 'onepage',
    name: 'Onepage',
    period: '',
    githubRepoName: [],
    skills: [
      'Android',
      'Retrofit2',
      'Butterknife',
      'Spring Boot',
      'QueryDSL',
      'SwaggerUI',
      'Mockito',
      'MySQL',
    ],
    summary: '위치기반 익명 SNS',
    githubUrl: 'https://github.com/OnePageAndroid',
    linkUrl:
      'https://play.google.com/store/apps/details?id=kr.nexters.onepage&hl=ko',
  },
  {
    id: 'intersection',
    name: 'Intersection',
    period: '',
    githubRepoName: [],
    skills: [
      'Android',
      'MaterialDesign',
      'GSON',
      'Spring Framework',
      'Hibernate',
      'PostgreSQL',
    ],
    summary: '너와 나의 중간지점',
    githubUrl: 'https://github.com/BoBinLee/map',
    linkUrl:
      'https://play.google.com/store/apps/details?id=com.nexters.intersection.intersectionapp',
  },
  {
    id: 'team42',
    name: 'Team42',
    period: '',
    githubRepoName: [],
    skills: ['Bootstrap', 'jQuery', 'velocity', 'lessJS'],
    summary: 'Team42 Site',
    githubUrl: '',
    linkUrl: 'http://team42.net/',
  },
  {
    id: 'skhualarm',
    name: 'Skhualarm',
    period: '',
    githubRepoName: [],
    skills: [
      'Android',
      'Facebook Graph API',
      'Picasso',
      'Gson',
      'Spring Framework',
      'MyBatis',
      'Jsoup',
      'Quartz',
      'MariaDB',
    ],
    summary: 'Sungkonghoe University Alarm App',
    githubUrl: 'https://github.com/BoBinLee/SkhuApp',
    linkUrl:
      'https://play.google.com/store/apps/details?id=com.skhu.bobinlee.skhuapp&hl=ko',
  },
  {
    id: 'competition',
    name: 'Competition',
    period: '',
    githubRepoName: [],
    skills: [
      'Bootstrap',
      'AngularJS',
      'LessJS',
      'jQuery',
      'Spring Framework',
      'Tiles',
      'MyBatis',
      'MariaDB',
    ],
    summary: 'Sungkonghoe University Competition Site',
    githubUrl: 'https://github.com/BoBinLee/SkhuCompetition.Server',
    linkUrl: '',
  },
  {
    id: 'softhome',
    name: 'Softhome',
    period: '',
    githubRepoName: [],
    skills: ['jQuery', 'PrototypeJs', 'JPageJs', 'JSP', 'MyBatis', 'RDB'],
    summary: 'Sungkonghoe University Software Engineering Department Site',
    githubUrl: 'https://github.com/BoBinLee/swhome',
    linkUrl: '',
  },
];

export { productions };
