backend:
  name: github
  repo: BoBeenLee/bbl
  branch: master
  preview_context: my-provider/deployment

media_folder: static/images
public_folder: /images

collections:
  - name: "Post"
    label: "Post"
    folder: "src/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {
          label: "Published",
          name: "published",
          widget: "boolean",
          default: false,
        }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Tags", name: "tags", widget: "list" }
